name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
jobs:
  release:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip release]')"

    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node 14.17.0
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.0

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
